SELECT * FROM HR.TCS.EMPLOYEES ;

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY,
       ROW_NUMBER() OVER(ORDER BY SALARY DESC ) AS RID,
       RANK()  OVER(ORDER BY SALARY DESC) AS RNK, 
       DENSE_RANK()  OVER(ORDER BY SALARY DESC) AS DRNK,
       LEAD(SALARY)  OVER(ORDER BY SALARY DESC) AS NEXT_VALUE ,
       LAG(SALARY) OVER(ORDER BY SALARY DESC) AS PREVIOUS_VALUE,
        FROM HR.TCS.EMPLOYEES ;



---FIND 5TH HIGHEST / 10 HIGHEST SALARY 

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY
       FROM HR.TCS.EMPLOYEES 
       ORDER BY SALARY DESC ; 


SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY,
       DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RNK
       FROM HR.TCS.EMPLOYEES ; 

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY,
       DENSE_RANK() OVER (ORDER BY SALARY ) AS RNK
       FROM HR.TCS.EMPLOYEES ; 

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY,
       DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DRNK
       FROM HR.TCS.EMPLOYEES ; 
        


-- CTE  -- COMMON TABLE EXPRATIONS -- IT WILL ACT AS LIKE TEMP TABLE/SESSION TABLES 


WITH CTE_EMP AS 
 (SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY,
       DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DRNK
       FROM HR.TCS.EMPLOYEES )
SELECT * FROM CTE_EMP 
  WHERE DRNK = 5 ;


WITH CTE_EMPS AS 
(SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY,
       DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DRNK
       FROM HR.TCS.EMPLOYEES )
    SELECT * FROM CTE_EMPS 
       WHERE DRNK = 20 ;


-- 2ND WAYS TO FIND  THE EXPRATION (QUALIFY SPECIALLY FOR SNOWFLAKE) 

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY,
       DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DRNK
       FROM HR.TCS.EMPLOYEES
       QUALIFY DRNK =  6 ;

--DEPARTMENTWISE 2ND HIGHEST SALARY  


SELECT EMPLOYEE_ID,
       FIRST_NAME,
       DEPARTMENT_ID,
       SALARY,
       DENSE_RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS DRNK
       FROM HR.TCS.EMPLOYEES ;


WITH ECT_EMP AS (
  SELECT EMPLOYEE_ID,
       FIRST_NAME,
       DEPARTMENT_ID,
       SALARY,
       DENSE_RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS DRNK
       FROM HR.TCS.EMPLOYEES 
)
    SELECT * FROM ECT_EMP WHERE DRNK = 2 ;



--SET OPERATOR  
-- UNION WILL REMOVE THE DUPLIDATES  

SELECT FIRST_NAME  FROM  HR.TCS.EMPLOYEES
  UNION 
SELECT FIRST_NAME FROM HR.TCS.DEPENDENTS ; 


-- UNION ALL IT WILL NOT REMOVE THE DUPICATE 

SELECT FIRST_NAME  FROM  HR.TCS.EMPLOYEES
  UNION ALL
SELECT FIRST_NAME FROM HR.TCS.DEPENDENTS ; 


-- INTERSECT IT WILL FATCH ONLY THE MATCHED VALUES FROM THE RESULTS 

SELECT FIRST_NAME  FROM HR.TCS.EMPLOYEES 
  INTERSECT
SELECT FIRST_NAME FROM HR.TCS.DEPENDENTS ;


-- MINUS THE DATA  SHOULD BE PRESENT IN  ONLY A TABLE NOT IN B TABLE  

SELECT FIRST_NAME  FROM HR.TCS.EMPLOYEES 
  MINUS
SELECT FIRST_NAME FROM HR.TCS.DEPENDENTS ;






CREATE TABLE monthly_sales (
    MID NUMBER(2),
    MONTH_NAME VARCHAR2(10),
    AMOUNT NUMBER(10)
);

INSERT INTO monthly_sales VALUES (1,  'JAN', 20000);
INSERT INTO monthly_sales VALUES (2,  'FEB', 30000);
INSERT INTO monthly_sales VALUES (3,  'MAR', 10000);
INSERT INTO monthly_sales VALUES (4,  'APR', 25000);
INSERT INTO monthly_sales VALUES (5,  'MAY', 35000);
INSERT INTO monthly_sales VALUES (6,  'JUN', 15000);
INSERT INTO monthly_sales VALUES (7,  'JUL', 40000);
INSERT INTO monthly_sales VALUES (8,  'AUG', 28000);
INSERT INTO monthly_sales VALUES (9,  'SEP', 32000);
INSERT INTO monthly_sales VALUES (10, 'OCT', 22000);
INSERT INTO monthly_sales VALUES (11, 'NOV', 38000);
INSERT INTO monthly_sales VALUES (12, 'DEC', 45000);

SELECT * 
FROM monthly_sales;

SELECT MID,
       MONTH_NAME,
       AMOUNT,
       LAG(AMOUNT) OVER (ORDER BY MID) AS PREVIOUS_MONTH,
       
       AMOUNT - LAG(AMOUNT) OVER (ORDER BY MID) AS DIFFERENCE,

       CASE
           WHEN AMOUNT > LAG(AMOUNT) OVER (ORDER BY MID)
               THEN 'PROFIT'
           WHEN AMOUNT < LAG(AMOUNT) OVER (ORDER BY MID)
               THEN 'LOSS'
           ELSE 'NO CHANGE'
       END AS PROFIT_OR_LOSS
FROM MONTHLY_SALES
ORDER BY MID;





