-- Fix missing comma between VALUES rows in multi-row INSERT
-- Co-authored with CoCo
create database ECOM_DEV ;

CREATE OR REPLACE  DATABASE COLLEGE ;

CREATE DATABASE VITECH_DEV ;

USE COLLEGE;

CREATE SCHEMA COLLEGE.MBA;

CREATE SCHEMA COLLEGE.MCA;

CREATE SCHEMA COLLEGE.BTECH;


CREATE TABLE COLLEGE.MBA.STUDENT (SID INT,
                      NAME STRING ,
                      ADRESS STRING ,
                      CLASS VARCHAR(20)
                      );


INSERT INTO COLLEGE.MBA.STUDENT (SID,NAME,ADRESS,CLASS) VALUES
                                 (101,'RAVI','BLR','MBA'),
                                 (102,'JHANU','HYD','MBA');



SELECT * FROM COLLEGE.MBA.STUDENT ;

ALTER TABLE COLLEGE.MBA.STUDENT DROP COLUMN  ADRESS ;

ALTER TABLE COLLEGE.MBA.STUDENT ADD COLUMN ADRESS STRING ;

ALTER TABLE COLLEGE.MBA.STUDENT ADD COLUMN MARK INT ;

UPDATE  COLLEGE.MBA.STUDENT
   SET MARK = 90
   WHERE SID = 101 ; 

   UPDATE  COLLEGE.MBA.STUDENT
   SET MARK = 85
   WHERE SID = 102 ; 

   SELECT * FROM COLLEGE.MBA.STUDENT ;

   UPDATE COLLEGE.MBA.STUDENT
   SET ADRESS = 'BLR';

   drop schema hr.region ;

   CREATE SCHEMA COLLEGE.Mits ;
   CREATE SCHEMA COLLEGE.Vit ;
   CREATE SCHEMA COLLEGE.SGMS ;

   CREATE OR REPLACE TABLE COLLEGE.MITS.STUDENT (
       SID INT,
       NAME STRING ,
       ADRESS STRING,
       MARKS INT,
       PHONE INT
   ) ;

     CREATE OR REPLACE TABLE COLLEGE.MITS.STUDENT (
       SID INT,
       NAME STRING ,
       ADRESS STRING,
       MARKS INT,
       PHONE INT
   ) ;

   INSERT INTO COLLEGE.MITS.STUDENT (SID,NAME,ADRESS,MARKS,PHONE) VALUES
   (101,'ANIL','BLR',96 ,960321),
   (102,'RAKESH','HYD',90 ,962321),
   (103,'BISHNU','DIL',85 ,961321),
   (104,'SAMAY','BLR',62 ,965321),
   (105,'KRISHNA','CHA',45 ,963321),
   (106,'DHRUB','PAT',49 ,964321),
   (107,'SONIAY','PAT',58 ,965321),
   (108,'VAIRAB','BLR',74 ,962321),
   (109,'OMPRAKASH','HYD',82 ,969321),
   (110,'ESTIN','BLR',68 ,943321) ;

DROP TABLE COLLEGE.MITS.STUDENT ;
undrop TABLE COLLEGE.MITS.STUDENT ;

DROP TABLE COLLEGE.MITS.STUDENT ;
DELETE FROM  COLLEGE.MITS.STUDENT ;
TRUNCATE TABLE COLLEGE.MITS.STUDENT ;



   SELECT * FROM COLLEGE.MITS.STUDENT ;

   SELECT * FROM COLLEGE.VIT.STUDENT ;

   SELECT * FROM COLLEGE.SGMS.STUDENT ;
