show tables;

SELECT * FROM HR.TCS.EMPLOYEES;


-- TOP 5
SELECT TOP 5 * FROM HR.TCS.EMPLOYEES ;

-- WHERE
SELECT TOP 5 * FROM HR.TCS.EMPLOYEES WHERE JOB_ID IN (4,5) ;

-- LIMIT 5 10,15
SELECT * FROM HR.TCS.EMPLOYEES 
        LIMIT 3 OFFSET 20 ;
        
SELECT * FROM HR.TCS.EMPLOYEES 
        LIMIT 5 OFFSET 0 ;
-- OFFSET

-- ORDER BY ACS/DESC

SELECT * FROM HR.TCS.EMPLOYEES 
    ORDER BY DEPARTMENT_ID ASC ;



SELECT * FROM HR.TCS.EMPLOYEES 
    ORDER BY DEPARTMENT_ID DESC ;

SELECT * FROM HR.TCS.EMPLOYEES 
    ORDER BY SALARY DESC ;


SELECT TOP 5  * FROM HR.TCS.EMPLOYEES 
    ORDER BY SALARY DESC ;

-- 3RD HIGHEST SALARY

SELECT  * FROM HR.TCS.EMPLOYEES 
    ORDER BY SALARY DESC
    LIMIT 1 OFFSET 3 ;

-- 10 HIGHEST SALARY

SELECT  * FROM HR.TCS.EMPLOYEES 
    ORDER BY SALARY DESC
    LIMIT 1 OFFSET 10 ;

-- BETWEEN 

SELECT * FROM HR.TCS.EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000 ;

-- IN
SELECT * FROM HR.TCS.EMPLOYEES WHERE DEPARTMENT_ID = 5;

SELECT * FROM HR.TCS.EMPLOYEES WHERE DEPARTMENT_ID IN (5,6,8);
-- <> <=>=
-- LIKE
SELECT FIRST_NAME  FROM HR.TCS.EMPLOYEES ; 

SELECT FIRST_NAME FROM HR.TCS.EMPLOYEES
WHERE FIRST_NAME LIKE 'D%' ;

SELECT FIRST_NAME FROM HR.TCS.EMPLOYEES
WHERE FIRST_NAME LIKE '%a' ;

SELECT FIRST_NAME FROM HR.TCS.EMPLOYEES
WHERE FIRST_NAME LIKE '%na' ;

-- DISTINCT

SELECT FIRST_NAME,DEPARTMENT_ID FROM HR.TCS.EMPLOYEES ; 

SELECT DISTINCT (DEPARTMENT_ID) FROM HR.TCS.EMPLOYEES ;

SELECT DISTINCT  FIRST_NAME,DEPARTMENT_ID FROM HR.TCS.EMPLOYEES ; 

SELECT DISTINCT * FROM HR.TCS.EMPLOYEES ; 


--AGGREGATE FUNCTIONS 

-- MAX ,MIN ,AVG , SUM , COUNT 


SELECT MAX(SALARY) FROM HR.TCS.EMPLOYEES ;

SELECT MIN (SALARY) FROM HR.TCS.EMPLOYEES ;

SELECT AVG(SALARY) FROM HR.TCS.EMPLOYEES ;

SELECT SUM(SALARY) FROM HR.TCS.EMPLOYEES ; 


SELECT COUNT(SALARY) FROM HR.TCS.EMPLOYEES ; 

select count(*) from hr.tcs.employees ;
SELECT COUNT(MANAGER_ID) FROM HR.TCS.EMPLOYEES ; 

--- All agregate functions in  a single querry   

select 
   MAX(salary) AS max_salary,
   MIN(salary) AS min_salary,
   AVG(salary) AS avg_salary,
   SUM(salary) AS sum_salary,
   COUNT(salary) AS count_salry,
   COUNT(*) AS count_all,
   COUNT(MANAGER_ID) AS count_manager_id
   FROM HR.TCS.EMPLOYEES ;


-- TO CHANGE THE COLLUMN NAME  

SELECT FIRST_NAME AS FNAME  FROM HR.TCS.EMPLOYEES ;


-- GROUP BY / HAVING 

SELECT DEPARTMENT_ID FROM HR.TCS.EMPLOYEES ;

SELECT DEPARTMENT_ID,COUNT(DEPARTMENT_ID) 
FROM HR.TCS.EMPLOYEES 
GROUP BY DEPARTMENT_ID ;

SELECT DEPARTMENT_ID,COUNT(DEPARTMENT_ID) AS CNT 
FROM HR.TCS.EMPLOYEES 
GROUP BY DEPARTMENT_ID 
ORDER BY 2 ;

-- HAVING 

SELECT DEPARTMENT_ID,COUNT(DEPARTMENT_ID) AS CNT 
FROM HR.TCS.EMPLOYEES 
GROUP BY DEPARTMENT_ID 
HAVING COUNT(DEPARTMENT_ID) >=5;

--DEPARTMENT WISE HIGHT SALARY 

SELECT DEPARTMENT_ID,MAX(SALARY) AS MAX_SALARY 
FROM HR.TCS.EMPLOYEES 
GROUP BY DEPARTMENT_ID ;


--DEPARTMENT WISE LOWEST SALARY 

SELECT DEPARTMENT_ID,MIN(SALARY) AS MIN_SALARY 
FROM HR.TCS.EMPLOYEES 
GROUP BY DEPARTMENT_ID ;

--DEPARTMENT WISE HOW MUCH PAY ?? 

SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY 
FROM HR.TCS.EMPLOYEES 
GROUP BY DEPARTMENT_ID ;

SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY 
FROM HR.TCS.EMPLOYEES 
GROUP BY DEPARTMENT_ID 
ORDER BY 2 DESC ;

-- TO FIND THE DUPLIUCATE  

SELECT FIRST_NAME, COUNT(*) FROM HR.TCS.EMPLOYEES 
GROUP BY FIRST_NAME ;

SELECT FIRST_NAME, COUNT(*) FROM HR.TCS.EMPLOYEES 
GROUP BY FIRST_NAME
HAVING COUNT(*) >=2 ;

SELECT FIRST_NAME, COUNT(*) FROM HR.TCS.EMPLOYEES 
GROUP BY FIRST_NAME
HAVING COUNT(*) > 1 ;

------------------PRACTICE 10 STRING , NUMBERS , DATE FUNCTIONS 


SELECT FIRST_NAME , UPPER(FIRST_NAME) FROM HR.TCS.EMPLOYEES ;

SELECT FIRST_NAME , LOWER (FIRST_NAME) FROM HR.TCS.EMPLOYEES ;


SELECT FIRST_NAME , SUBSTR(FIRST_NAME,0,3)  FROM HR.TCS.EMPLOYEES ;


SELECT CONCAT(FIRST_NAME,' ',LAST_NAME ) AS FNAME  FROM HR.TCS.EMPLOYEES ; 



SELECT FIRST_NAME , REVERSE(FIRST_NAME)  FROM HR.TCS.EMPLOYEES ;

SELECT CURRENT_DATE();

SELECT CURRENT_TIMESTAMP() ;


SELECT CURRENT_DATE AS today;

SELECT EXTRACT(YEAR FROM hire_date) AS hire_year
FROM employees;

SELECT EXTRACT(MONTH FROM hire_date) AS hire_month
FROM employees;


SELECT EXTRACT(DAY FROM hire_date) AS hire_day
FROM employees;

SELECT hire_date + INTERVAL '10' DAY AS new_date
FROM employees;

SELECT *
FROM employees
WHERE hire_date > DATE '1994-01-01';

SELECT *
FROM employees
WHERE EXTRACT(YEAR FROM hire_date) = 1997;

SELECT CURRENT_DATE - hire_date AS days_worked
FROM employees;

SELECT LAST_DAY(hire_date) AS month_end
FROM employees;

SELECT TO_CHAR(hire_date, 'DD-MM-YYYY') AS formatted_date
FROM employees;

select * from employees ;


SELECT ROUND(salary, 2) AS rounded_salary
FROM employees;

SELECT CEIL(salary) AS salary_ceil
FROM employees;

SELECT FLOOR(salary) AS salary_floor
FROM employees;

SELECT ABS(-500) AS result;


SELECT MOD(employee_id, 2) AS remainder
FROM employees;

SELECT POWER(2, 3) AS result;

SELECT SQRT(144) AS result;

SELECT TRUNC(salary, 2) AS truncated_salary
FROM employees;

SELECT GREATEST(100, 250, 150) AS greatest_value;

SELECT UPPER(first_name) AS name
FROM employees;

SELECT first_name, LENGTH(first_name) AS name_length
FROM employees;

SELECT CONCAT(first_name, ' ', last_name) AS full_name
FROM employees;

SELECT SUBSTR(first_name, 1, 3) AS short_name
FROM employees;

SELECT TRIM(first_name) AS cleaned_name
FROM employees;

SELECT LPAD(employee_id, 5, '0') AS employee_code
FROM employees;

SELECT RPAD(first_name, 15, '*') AS padded_name
FROM employees;